name: GIST CD on main branch and example directory change

# Check if files have been pushed to ./examples
on:
  push:
    paths:
      - python/**
      - curl/**

jobs:
  build:
    if: github.ref == 'refs/heads/main'

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.8']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install gistyc
      run: pip install repo-gist-sync

    - name: Use gistyc CLI on "python" directory
      run: gistdirsync --auth-token ${{ secrets.GIST_TOKEN }} --directory ./python/

    - name: Use gistyc CLI on "curl" directory
      run: gistdirsync --auth-token ${{ secrets.GIST_TOKEN }} --directory ./curl/